language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 2.7
      env: TOX_ENV=py27-configparser
    - python: 3.3
      env: TOX_ENV=py33
    - python: 3.3
      env: TOX_ENV=py33
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35
    - python: pypy
      env: TOX_ENV=pypy

install:
  - git config --global user.email "bumpversion-test-git@travis.ci"
  - git config --global user.name "Testing Git on Travis CI"
  - git --version
  - git config --list
  - echo -e '[ui]\nusername = Testing Mercurial on Travis CI <bumpversion-test-hg@travis.ci>' > ~/.hgrc
  - hg --version
  - pip install --upgrade pytest tox

script:
  - tox -e $TOX_ENV

